data:
  FUNCTIONS_WORKER_RUNTIME: "ZG90bmV0"
  ClaimsPostQueue: "{{ .Values.function.azServiceBusInpQueue }}"
  ClaimsDelQueue: "{{ .Values.function.azServiceBusDelQueue }}"
  ClaimsApiHost: "{{ .Values.function.claimsApiHost }}"
  ClaimsApiEndpoint: "{{ .Values.function.claimsApiEndpoint }}"
apiVersion: v1
kind: Secret
metadata:
  name: claims-api-func
